apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
  namespace: syncthing
spec:
  type: LoadBalancer
  selector:
    app: syncthing
  ports:
  - name: tcp-22000
    port: 22000
    targetPort: 22000
    protocol: TCP
  - name: udp-22000
    port: 22000
    targetPort: 22000
    protocol: UDP
  - name: udp-21027
    port: 21027
    targetPort: 21027
    protocol: UDP
  - name: tcp-8384
    port: 8384
    targetPort: 8384
    protocol: TCP
# status:
#   loadBalancer:
#     ingress:

