---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: syncthing-config-pv
  labels:
    app: syncthing
    type: config
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.nfs-provisioner.svc.cluster.local/#syncthing#config
    volumeAttributes:
      server: nfs-server.nfs-provisioner.svc.cluster.local
      share: /syncthing/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: syncthing-data-pv
  labels:
    app: syncthing
    type: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-server.nfs-provisioner.svc.cluster.local/#syncthing#data
    volumeAttributes:
      server: nfs-server.nfs-provisioner.svc.cluster.local
      share: /syncthing/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 128Mi
  selector:
    matchLabels:
      app: syncthing
      type: config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: syncthing
      type: data