---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config-pv
  labels:
    app: syncthing
    type: config
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: syncthing-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data-pv
  labels:
    app: syncthing
    type: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: syncthing-data-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      app: syncthing
      type: config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: syncthing
      type: data