Vagrant.configure("2") do |config|
    config.vm.box = "rhel92"
    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 4
        libvirt.memory = 4096
        libvirt.qemu_use_session = false
    end
    config.nfs.verify_installed = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provision "file", source: "~/.ssh/vagrant.pub", destination: "/tmp/vagrant.pub"
    config.vm.provision "shell", inline: "cat /tmp/vagrant.pub >> /home/vagrant/.ssh/authorized_keys"

    config.trigger.before :destroy do |trigger|
        trigger.run_remote = {inline: "sudo subscription-manager unregister"}
    end

    config.vm.define :vagrant1 do |vagrant1|
        vagrant1.vm.network :private_network,
        :libvirt_network_address => "192.168.33.0",
        :ip => "192.168.33.130"
    end
    config.vm.define :vagrant2 do |vagrant2|
        vagrant2.vm.network :private_network,
        :libvirt_network_address => "192.168.33.0",
        :ip => "192.168.33.131"
    end
end