---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: discord-calendar
data:
  nginx.conf: |
    user  nginx; worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        types {
            text/css css;
            text/javascript js;
            application/javascript js;
            text/html html htm;
            application/json json;
        }

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        #gzip  on;
        server {
            listen 80;
            server_name calendar.jakubchyla.com;
            return 301 https://$host$request_uri;
        }
        server {
            listen 443 ssl;
            server_name calendar.jakubchyla.com;

            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            location / {
                alias /website/;
                index index.html;
                try_files $uri $uri/ /index.html;


                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
            }

        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-calendar-deployment
  namespace: discord-calendar
spec:
  selector:
    matchLabels:
      app: discord-calendar
  template:
    metadata:
      labels:
        app: discord-calendar
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          env:
            - name: "VOLUME_WEBSITE"
              value: "/website"
            - name: "VOLUME_DATA"
              value: "/calendar"
          command:
            - sh
            - -c
            - |
              chown -R 101:101 $VOLUME_WEBSITE
              chown -R 1000:1000 $VOLUME_DATA
              chmod 755 $VOLUME_WEBSITE
              chmod 644 $VOLUME_WEBSITE/*
              chmod 755 $VOLUME_DATA
              chmod 644 $VOLUME_DATA/*
              printf "%s\n" "set volumes ownership"
          volumeMounts:
          - mountPath: /website
            name: discord-calendar-website
          - mountPath: /calendar
            name: discord-calendar-calendar
      containers:
        - name: discord-calendar-nginx
          image: nginx:alpine
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          volumeMounts:
          - name: discord-calendar-website
            mountPath: /website
            readOnly: true
          - name: discord-calendar-nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          - name: discord-calendar-calendar
            mountPath: /calendar
            readOnly: true
          - name: cert
            mountPath: /etc/nginx/ssl

        - name: discord-calendar-bot
          image: jakchyla/calendar_bot:1.1
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-calendar-token-secret
                  key: discord-bot-token
            - name: CALENDAR_PATH
              value: /calendar/calendar.json
          volumeMounts:
          - mountPath: /calendar
            name: discord-calendar-calendar
            readOnly: false
      volumes:
        - name: discord-calendar-website
          persistentVolumeClaim:
            claimName: discord-calendar-website-pvc
        - name: discord-calendar-nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: discord-calendar-calendar
          persistentVolumeClaim:
            claimName: discord-calendar-calendar-pvc
        - name: cert
          secret:
            secretName: calendar-jakubchyla-com-tls
