- name: Copy kubeconfig from default path
  when: k3s_control_node

  block:
    - name: Check if .kube directory exists
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.kube/"
      register: kube

    - name: Create .kube directory exists
      when: not kube.stat.exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "700"

    - name: Check if kubeconfig exists
      ansible.builtin.stat:
        path: "~/.kube/config"
      register: config

    - name: Copy kubeconfig
      when: not config.stat.exists
      ansible.builtin.copy:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "600"
        remote_src: true
