- name: Get variable
  ansible.builtin.debug:
    var: k3s_control_node

- name: Setup k3s
  ansible.builtin.import_role:
    name: xanmanning.k3s

- name: Copy cluster config to host
  when: k3s_control_node
  ansible.builtin.fetch:
    dest: "~/tmp/"
    src: "/etc/rancher/k3s/k3s.yaml"
    flat: true

- name: Setup automatic updates
  block:
    - name: Copy k3s automatic updates files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "755"
        owner: "root"
        group: "root"
      loop:
        - src: "k3s-upgrade.service"
          dest: "/etc/systemd/system/k3s-upgrade.service"
        - src: "k3s-upgrade.timer"
          dest: "/etc/systemd/system/k3s-upgrade.timer"
        - src: "k3s-upgrade.sh"
          dest: "/usr/local/bin/k3s-upgrade.sh"
    - name: Enable automatic updates
      ansible.builtin.systemd:
        name: "k3s-upgrade.timer"
        state: "started"
        enabled: true
