---

- name: Check if helm is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/helm"
  register: st

- name: Ensure helm installed
  when: not st.stat.exists

  block:
    - name: Download helm
      ansible.builtin.get_url:
        url: "https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz"
        dest: "/tmp/helm.tar.gz"
        checksum: "sha256:1b2313cd198d45eab00cc37c38f6b1ca0a948ba279c29e322bdf426d406129b5"
        mode: "755"
        owner: root
        group: root


    - name: Unpack helm archive
      ansible.builtin.unarchive:
        src: "/tmp/helm.tar.gz"
        dest: "/usr/local/bin"
        extra_opts: "--strip-components=1"
        mode: "755"
        owner: root
        group: root
        remote_src: true
