- name: Download k3s install script
  ansible.builtin.get_url:
    url: "https://get.k3s.io/"
    dest: /usr/local/bin/k3s-install.sh
    owner: root
    group: root
    mode: "0755"

- name: Install k3s control node
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    K3S_TOKEN: "{{ k3s_token }}"
  when: k3s_control_node is defined
  changed_when: true

- name: Install k3s agent
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    K3S_URL: "{{ k3s_url }}"
    K3S_TOKEN: "{{ k3s_token }}"
  when: k3s_control_node is undefined
  changed_when: true

- name: Download kubeconfig
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/tmp
  when: k3s_control_node is defined
