---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-server
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeName: hades
      containers:
        - name: nfs-server
          image: jakchyla/nfs_server:latest
          imagePullPolicy: Always
          env:
            - name: SHARED_DIRECTORY
              value: "/exports"
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
          securityContext:
            privileged: true
          ports:
            - name: nfs
              containerPort: 2049
      volumes:
        - name: nfs-vol
          hostPath:
            path: /kubernetes/nfs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs-provisioner
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
  type: ClusterIP