- name: Prevent sleeping, suspend and hibernate
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
  loop:
    - "sleep.target"
    - "suspend.target"
    - "hibernate.target"
    - "hybrid-sleep.target"
