all:
  vars:
    config_dir: "/data/config_files"
    k3s_nodes:
      - 192.168.0.150
      - 192.168.0.151
  children:
    control_nodes:
      vars:
        k3s_control_node: true
      hosts:
        hades:
          ansible_host: 192.168.0.150
          ansible_user: ansible
          host_specific_packages:
            - "nfs-utils"
          nas: true

    managed_nodes:
      hosts:
        charon:
          ansible_host: 192.168.0.151
          ansible_user: ansible
