- name: Install packages
  become: true
  become_user: root
  hosts: all
  roles:
    - install_packages

- name: Configure network
  tags: network
  become: true
  become_user: root
  hosts: all
  roles:
    - network

- name: Install and configure k3s
  tags: k3s
  become: true
  become_user: root
  hosts: all
  roles:
    - k3s

# - name: Install helm charts
#   tags: helm_charts
#   hosts: all
#   vars_files:
#     - vars.yaml
#   roles:
#     - install_helm_charts
