name: exim4 Image Build and Upload

on:
    push:
        branches: ["master"]
        paths:
            - 'news/exim4/**'

jobs:
    push:
        uses: ./.github/workflows/docker_publish_image.yml
        with:
            build_path: ./news/exim4
            image_name: exim4
        secrets:
            dockerhub_user: ${{secrets.dockerhub_user}}
            dockerhub_access_token: ${{secrets.dockerhub_access_token}}