name: Syncthing Image Build and Upload

on:
    push:
        branches: ["master"]
        paths:
            - 'syncthing/**'

jobs:
    push:
        uses: ./.github/workflows/docker_publish.image.yml
        with:
            build_path: ./syncthing/build
            image_name: syncthing
        secrets:
            dockerhub_user: ${{secrets.dockerhub_user}}
            dockerhub_access_token: ${{secrets.dockerhub_access_token}}